version: "4.0"
services:
  postgres:
    image: postgres:15.12 # such version is on prod now
    container_name: klibs-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=klibs
      - POSTGRES_USER=klibs
      - POSTGRES_PASSWORD=klibs
    networks:
      - klibs-net

  localstack:
    image: localstack/localstack:latest
    container_name: klibs-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEFAULT_REGION: eu-west-1
    volumes:
      - ./docker-compose-volumes/localstack-data:/var/lib/localstack
    networks:
      - klibs-net

  opensearch:
    image: opensearchproject/opensearch:3.7.0
    container_name: klibs-opensearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch!ocalPassw0rd
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./docker-compose-volumes/opensearch-data:/usr/share/opensearch/data
    networks:
      - klibs-net
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail -k -u admin:OpenSearch!ocalPassw0rd https://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  s3-init:
    image: amazon/aws-cli:latest
    depends_on:
      - localstack
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-west-1
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo 'Creating S3 bucket...' &&
      aws --endpoint-url=http://localstack:4566 s3 mb s3://local-bucket
      "
    networks:
      - klibs-net

volumes:
  localstack-data:
  opensearch-data:

networks:
  klibs-net:
    driver: bridge