logging:
  level:
    io.klibs: ${KLIBS_LOGGING_LEVEL:INFO}

spring:
  datasource:
    url: ${DB0_URL_JDBC}
    username: ${DB0_USERNAME}
    password: ${DB0_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 9
  ai:
    openai:
      api-key: ${KLIBS_OPENAPI_KEY}
      chat:
        options:
          model: gpt-4o
    mcp:
      server:
        name: klibs-mcp-server
        version: 1.0.0
        protocol: stateless
    retry:
      max-attempts: 1
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      enabled: false
  profiles:
    active: local
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          max-age: 24h
          must-revalidate: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION:eu-west-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      endpoint: ${GCS_ENDPOINT}
      s3:
        checksum-validation-enabled: false

klibs:
  ai: ${KLIBS_AI_GENERATION_ENABLED:false}
  api-docs:
    title: "klibs.io"
    description: "API endpoints"
  readme:
    cache-dir: ${KLIBS_CACHE_DIR_README:${user.dir}/cache/readme}
    s3:
      bucket-name: ${BUCKET_NAME}
      prefix: ${KLIBS_README_S3_PREFIX:readme}
    reprocess-period-days: 6
  integration:
    maven:
      central:
        discovery-endpoint: ${KLIBS_MAVEN_CENTRAL_DISCOVERY_ENDPOINT}
        rate-limit-capacity: ${KLIBS_MAVEN_RATE_LIMIT_CAPACITY:5}
        rate-limit-refill-amount: ${KLIBS_MAVEN_RATE_LIMIT_REFILL_AMOUNT:2}
        rate-limit-refill-period-sec: ${KLIBS_MAVEN_RATE_LIMIT_REFILL_PERIOD:5}
        index-endpoint: ${KLIBS_MAVEN_INDEX_ENDPOINT:https://repo1.maven.org/maven2}
        index-dir: ${KLIBS_MAVEN_INDEX_CACHE_DIR:${user.dir}/cache/maven-index}
        content-endpoint: ${KLIBS_MAVEN_CONTENT_ENDPOINT:https://repo1.maven.org/maven2/}
        content-fallback-endpoint: ${KLIBS_MAVEN_CONTENT_FALLBACK_ENDPOINT:https://search.maven.org/remotecontent?filepath=}
    github:
      personal-access-token: ${KLIBS_GITHUB_TOKEN:}
      app:
        client-id: ${KLIBS_GITHUB_APP_CLIENT_ID:}
        installation-id: ${KLIBS_GITHUB_APP_INSTALLATION_ID:0}
        #NOTE: we need a PKCS8 format, GitHub by default uses PKCS1.
        # Thus, you need to convert it before and remove the header and footer (BEGIN/END PRIVATE KEY)
        private-key: ${KLIBS_GITHUB_APP_PRIVATE_KEY:}
      cache:
        request-cache-path: ${KLIBS_CACHE_DIR_REQUESTS:${user.dir}/cache/request-cache}
        request-cache-size-mb: ${KLIBS_CACHE_DIR_REQUEST_SIZE_MB:10}
      update-repos-per-iteration: ${KLIBS_UPDATE_GITHUB_REPOS_PER_ITERATION:3}
      index-requests:
        repository: ${KLIBS_GITHUB_REPOSITORY:}
        request-label: ${KLIBS_GITHUB_REQUEST_LABEL:index-request}
        processed-label: ${KLIBS_GITHUB_PROCESSED_LABEL:triaged}
        developer-handle: ${KLIBS_GITHUB_DEVELOPER_HERO:}
      webhook:
        secret: ${KLIBS_GITHUB_WEBHOOK_SECRET:}
  indexing: ${KLIBS_ENABLE_INDEXING:false}
  search:
    opensearch:
      request-timeout: ${KLIBS_OPENSEARCH_REQUEST_TIMEOUT:30s}
  scheduling:
    process-indexing-queue:
      enabled: ${PROCESS_INDEXING_QUEUE_ENABLED:true}
    fill-version-type:
      enabled: ${FILL_VERSION_TYPE_ENABLED:true}
    search-index-sync:
      enabled: ${SEARCH_INDEX_SYNC_ENABLED:true}
  indexing-configuration:
    executor:
      thread-count: 2
    retry:
      max-attempts: ${KLIBS_INDEXING_MAX_ATTEMPTS:2}
    reporting:
      index-defer: ${KLIBS_REPORTING_INDEX_DEFER:10m}
    description:
      regen-ttl: ${KLIBS_DESCRIPTION_REGEN_TTL:90d}
    central-sonatype:
      enabled: ${KLIBS_ENABLE_INDEXING_CENTRAL_SONATYPE:false}
    gmaven:
      enabled: ${KLIBS_ENABLE_INDEXING_GMAVEN:false}
      s3:
        bucket-name: ${BUCKET_NAME}
        prefix: ${KLIBS_GMAVEN_S3_PREFIX:gmaven}
  oss-health:
    commit-cv-denominator: 3.0
    issue-median-days-threshold: 21.0
    pr-median-days-threshold: 10.0
    active-contributors-target: 5

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics, scheduledtasks, prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
    prometheus:
      access: read_only
  info:
    git.enabled: true
    os.enabled: true
    java.enabled: true

springdoc:
  swagger-ui:
    default-models-expand-depth: 1
    path: /api-docs/swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
    persist-authorization: true
  api-docs:
    path: /api-docs/v3
  disable-i18n: true

server:
  compression:
    enabled: true
